version: '3'
services:

  # MySQL
  mi-mysql:
    image: mysql:latest
    container_name: mi-mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3336:3306
    environment:
      MYSQL_DATABASE: my_pf_api
      MYSQL_ROOT_PASSWORD: 123123123
      SERVICE_TAGS: docker
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql-files:/var/lib/mysql-files
      - dbdata:/var/lib/mysql
    networks:
      - mi-network

  # Nginx
  mi-nginx:
    image: nginx:alpine
    container_name: mi-nginx
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_TAGS: docker
      SERVICE_NAME: nginx
    ports:
      - "${LISTEN_IP}:80:80"
    depends_on:
      - mi-frontend
      - mi-backend
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    networks:
      - mi-network

  # PHP-FPM with backend
  mi-backend:
    container_name: mi-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /app
    depends_on:
      - mi-mysql
    volumes:
      - "${BACKEND_DIR}:/app"
    environment:
      SERVICE_NAME: backend
      SERVICE_TAGS: docker
    networks:
      - mi-network

  # Vue-cli with frontend
  mi-frontend:
    container_name: mi-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - "${FRONTEND_DIR}:/app"
    environment:
      SERVICE_NAME: frontend
      SERVICE_TAGS: docker
      NODE_ENV: development
    networks:
      - mi-network

  # PHPMyAdmin Setup
  phpmyadmin:
    image: phpmyadmin:5.1.0-apache
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8200:80
    environment:
      PMA_HOST: mi-mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123123123
    networks:
      - mi-network

# networks
networks:
  mi-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "${LISTEN_IP}"

# volume to store DB files
volumes:
  dbdata:
    driver: local